### ISSUE TITLE
generate video

### ISSUE THREAD

**Issue by mzhng** [jupyter-widgets/pythreejs#167]
Is there a recommended way to efficiently make a video from a pythreejs animation? I'd like to set up a scene, render several frames and ideally send them to some python ffmpeg wrapper, although I don't know if this even makes sense since everything is rendered in the browser and I guess there's no direct way to make a pipe between the renderer and an ffmpeg process. Any recommendations?

**Comment by vidartf** [comment]
There isn't currently any official way of doing this. You might want to follow [this answer](https://stackoverflow.com/a/26236237/4779440) though: Use a browser extension to record a video from the browser canvas. I'll leave this open for in order to mark that more "integrated" solutions should still be explored.
