### ISSUE TITLE
verticesNeedUpdate

### ISSUE THREAD

**Issue by jacksonloper** [jupyter-widgets/pythreejs#234]
I think `Geometry` objects should have a boolean trait 

verticesNeedUpdate

so that if we update a geometry we can tell threejs to update everything's placement.  As is I don't see a way to update the vertices of a Geometry object.  Thanks!

**Comment by vidartf** [comment]
I think [this line](https://github.com/jupyter-widgets/pythreejs/blob/0289714e141bfaee2183d8554d0cbc01d32eb594/js/src/core/Geometry.js#L46) should handle that. It is something that we should get for free since Widgets are event based. However, note that python containers are not eventful, so to update the vertices you cannot modify the vertices in-place! You need to create a copy, modify that copy, and then assign the copy back to the widget. It is a common issue across widgets unfortunately.

**Comment by vidartf** [comment]
Closing due to lack of feedback. I will reopen if there is some additional points here, though!
